apiVersion: v1
kind: Pod
metadata:
  name: pod-huge
  namespace: dev
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      resources:
        requests:
          cpu: "2"
          memory: "128Mi"
        limits:
          cpu: "4"
          memory: "256Mi"
